title: GIFTbench Docs
description: Full documentation for GIFTbench
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

# Optional polish
logo: # /assets/images/logo.png
color_scheme: light
search_enabled: true
aux_links:
  View on GitHub: https://deeptestai.github.io/genai_tigs/
